apiVersion: v1
kind: Service
metadata:
  name: build2018-rating-web
  labels:
    name: build2018-rating-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: build2018-rating-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: build2018-rating-web
  name: build2018-rating-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build2018-rating-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: build2018-rating-web
    spec:
      containers:
      - env:
        - name: SITE_API
          value: "http://build2018-api-sites:8080/"
        - name: SUBJECT_API
          value: "http://build2018-api-subjects:8080/"
        - name: RATING_API
          value: "http://build2018-api-ratings:8080/"
        image: krypton.azurecr.io/gab/webv2:v2
        imagePullPolicy: Always
        name: build2018-rating-web
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
